//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mkWritable.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("mkWritable.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} {1}
        ///
        ///Remove write protection from Word or Excel files (docx/xlsx).
        ///
        ///Usage: {0}.exe argument
        ///
        ///Arguments:
        ///                     path to a .docx/.xlsx file
        ///                     /register (register in context menu)
        ///                     /unregister (unregister from context menu) ähnelt.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die About mkWritable ähnelt.
        /// </summary>
        internal static string AboutMkWritable {
            get {
                return ResourceManager.GetString("AboutMkWritable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An error occurred:  ähnelt.
        /// </summary>
        internal static string AnErrorOccurred {
            get {
                return ResourceManager.GetString("AnErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Application registered in users context menu. ähnelt.
        /// </summary>
        internal static string ApplicationRegisteredInUsersContextMenu {
            get {
                return ResourceManager.GetString("ApplicationRegisteredInUsersContextMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Application unregistered from users context menu. ähnelt.
        /// </summary>
        internal static string ApplicationUnregisteredFromUsersContextMenu {
            get {
                return ResourceManager.GetString("ApplicationUnregisteredFromUsersContextMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove write protection ähnelt.
        /// </summary>
        internal static string MakeWritable {
            get {
                return ResourceManager.GetString("MakeWritable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Icon ähnlich wie (Symbol).
        /// </summary>
        internal static System.Drawing.Icon mkWritable {
            get {
                object obj = ResourceManager.GetObject("mkWritable", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No sheet*.xml files found. ähnelt.
        /// </summary>
        internal static string NoSheetXmlFilesFound {
            get {
                return ResourceManager.GetString("NoSheetXmlFilesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No write protection found in {0}. ähnelt.
        /// </summary>
        internal static string NoWriteProtectionFoundIn0 {
            get {
                return ResourceManager.GetString("NoWriteProtectionFoundIn0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Process completed. New Excel file saved at:  ähnelt.
        /// </summary>
        internal static string ProcessCompletedNewExcelFileSavedAt {
            get {
                return ResourceManager.GetString("ProcessCompletedNewExcelFileSavedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Process completed. New Word file saved at:  ähnelt.
        /// </summary>
        internal static string ProcessCompletedNewWordFileSavedAt {
            get {
                return ResourceManager.GetString("ProcessCompletedNewWordFileSavedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The file &apos;{0}&apos; does not exist. ähnelt.
        /// </summary>
        internal static string TheFile0DoesNotExist {
            get {
                return ResourceManager.GetString("TheFile0DoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The settings.xml file could not be found. ähnelt.
        /// </summary>
        internal static string TheSettingsXmlFileCouldNotBeFound {
            get {
                return ResourceManager.GetString("TheSettingsXmlFileCouldNotBeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The worksheets folder could not be found. ähnelt.
        /// </summary>
        internal static string TheWorksheetsFolderCouldNotBeFound {
            get {
                return ResourceManager.GetString("TheWorksheetsFolderCouldNotBeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unsupported file type. Only .xlsx and .docx are supported. ähnelt.
        /// </summary>
        internal static string UnsupportedFileTypeOnlyXlsxAndDocxAreSupported {
            get {
                return ResourceManager.GetString("UnsupportedFileTypeOnlyXlsxAndDocxAreSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Write protection found and removed in {0}. ähnelt.
        /// </summary>
        internal static string WriteProtectionFoundAndRemovedIn0 {
            get {
                return ResourceManager.GetString("WriteProtectionFoundAndRemovedIn0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Write protection removed from {0}. ähnelt.
        /// </summary>
        internal static string WriteProtectionRemovedFrom0 {
            get {
                return ResourceManager.GetString("WriteProtectionRemovedFrom0", resourceCulture);
            }
        }
    }
}
